name: "Setup Node.js"
description: "Set up a Node.js environment and add it to the PATH"
author: "Mock GitHub"

inputs:
  node-version:
    description: "Node.js version to use"
    required: false
    default: "20"
  cache:
    description: "Package manager to cache dependencies"
    required: false

runs:
  using: "composite"
  steps:
    - name: Mock Setup Node.js
      shell: bash
      run: |
        echo "Mock: Setting up Node.js ${{ inputs.node-version }}"
        # Create mock directories and commands
        mkdir -p "$HOME/.mock/node/bin"

        # Create mock executables
        cat > "$HOME/.mock/node/bin/node" << 'EOF'
        #!/bin/bash
        echo "Node.js ${{ inputs.node-version }} [mock]"
        EOF

        cat > "$HOME/.mock/node/bin/npm" << 'EOF'
        #!/bin/bash
        echo "npm [mock]"
        if [[ "$1" == "ci" ]]; then
          echo "Mock installing dependencies"
        fi
        EOF

        # Make executables runnable
        chmod +x "$HOME/.mock/node/bin/node"
        chmod +x "$HOME/.mock/node/bin/npm"

        # Add to PATH
        echo "PATH=$HOME/.mock/node/bin:$PATH" >> $GITHUB_ENV

        echo "Node.js mock setup complete"
