version: 2
updates:
  # Elixir dependencies
  - package-ecosystem: "mix"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 5
    reviewers:
      - "droo"
    labels:
      - "dependencies"
      - "elixir"
    groups:
      dev-dependencies:
        patterns:
          - "credo"
          - "dialyxir"
          - "ex_doc"
          - "excoveralls"
          - "mix_audit"
          - "sobelow"
      test-dependencies:
        patterns:
          - "stream_data"
          - "propcheck"
          - "mox"
    commit-message:
      prefix: "chore"
      include: "scope"
    
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 3
    reviewers:
      - "droo"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"
    
  # NPM dependencies (if VSCode extension exists)
  - package-ecosystem: "npm"
    directory: "/extensions/vscode"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 3
    reviewers:
      - "droo"
    labels:
      - "dependencies"
      - "javascript"
    ignore:
      # Ignore major version updates for critical packages
      - dependency-name: "vscode"
        update-types: ["version-update:semver-major"]
    commit-message:
      prefix: "chore"
      include: "scope"
    
  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2
    reviewers:
      - "droo"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "build"
      include: "scope"