codecov:
  require_ci_to_pass: false
  
coverage:
  precision: 2
  round: down
  range: "90...100"
  
  status:
    project:
      default:
        target: 95%
        threshold: 1%
        paths:
          - "lib/"
    patch:
      default:
        target: 90%
        threshold: 1%
        
parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false

ignore:
  - "test/**/*"
  - "**/*_test.exs"
  - "bench/**/*"
  - "examples/**/*"
  - "guides/**/*"
  - "scripts/**/*"
  - "config/**/*"
  - "priv/**/*"