name = "raxol-playground"
compatibility_date = "2024-09-26"
pages_build_output_dir = "web/priv/static"

[env.production]
name = "raxol-playground"
[env.production.vars]
MIX_ENV = "prod"
PHX_SERVER = "true"
NODE_VERSION = "20.10.0"
ERLANG_VERSION = "27.0"
ELIXIR_VERSION = "1.17.3"

[env.preview]
name = "raxol-playground-preview"
[env.preview.vars]
MIX_ENV = "prod"
PHX_SERVER = "true"
NODE_VERSION = "20.10.0"
ERLANG_VERSION = "27.0"
ELIXIR_VERSION = "1.17.3"

# Functions for SSR (if needed later)
# [functions]
# directory = "functions"