defmodule RaxolPlayground.RecordedFrames do
  @moduledoc """
  Recorded terminal frames served statically: the landing hero's switchable
  examples and one rendered preview per gallery demo.

  Generated by `scripts/gen_landing_frames.exs` at the repo root (real
  `Raxol.Headless` sessions rendered through `TerminalBridge.buffer_to_html/2`)
  and committed under `priv/hero_frames/` and `priv/demo_previews/`. Embedded
  at compile time so the dead render before the LiveView socket connects
  already carries frame one and every gallery preview.

  An example directory holds two sequences and one still. `frame_NN.html` is
  the terminal pane and `ansi_NN.ansi` is the same buffer as the bytes the SSH
  surface writes -- one of each per captured frame, so the two panes step
  together. `surface.mcp.json` is the tree the MCP surface serves, projected
  from frame zero: a structure rather than a picture, and the same in every
  frame. The browser surface needs no artifact of its own, because
  `frame_NN.html` IS the LiveView encoding: that pane renders the same sequence
  the terminal pane steps, inside a page, rather than deriving anything.

  `interval_ms` carries the tick the recording was sampled at, which is what
  the page plays it back at.
  """

  alias RaxolPlayground.SurfaceSource

  hero_dir = Path.expand("../../priv/hero_frames", __DIR__)
  preview_dir = Path.expand("../../priv/demo_previews", __DIR__)

  # One directory per hero example. The generator zero-pads frame names, which
  # is what lets this sort them lexically now that a recording runs to dozens
  # of frames -- unpadded, frame_10 would play before frame_2.
  hero_examples =
    hero_dir
    |> File.ls!()
    |> Enum.sort()
    |> Enum.filter(&File.dir?(Path.join(hero_dir, &1)))

  # Matched by name: the surface artifacts share this directory, and folding
  # one into the playback list would put an ANSI dump where a frame belongs.
  hero_paths =
    Map.new(hero_examples, fn name ->
      dir = Path.join(hero_dir, name)

      paths =
        dir
        |> Path.join("frame_*.html")
        |> Path.wildcard()
        |> Enum.sort()

      {name, paths}
    end)

  # The SSH pane animates, so its artifact is a sequence, not a still. Same
  # padding and the same lexical sort as the terminal frames, and the counts
  # match by construction: the generator writes one of each per captured buffer.
  ansi_paths =
    Map.new(hero_examples, fn name ->
      paths =
        hero_dir
        |> Path.join(name)
        |> Path.join("ansi_*.ansi")
        |> Path.wildcard()
        |> Enum.sort()

      {name, paths}
    end)

  surface_paths =
    Map.new(hero_examples, fn name ->
      dir = Path.join(hero_dir, name)

      {name,
       %{
         ansi: ansi_paths |> Map.fetch!(name) |> List.first(),
         mcp: Path.join(dir, "surface.mcp.json")
       }}
    end)

  for {_name, paths} <- hero_paths, path <- paths do
    @external_resource path
  end

  for {_name, %{ansi: ansi, mcp: mcp}} <- surface_paths, path <- [ansi, mcp] do
    @external_resource path
  end

  for {_name, paths} <- ansi_paths, path <- paths do
    @external_resource path
  end

  @hero_frames Map.new(hero_paths, fn {name, paths} ->
                 {name, Enum.map(paths, &File.read!/1)}
               end)

  # The interval the recorder sampled at, written beside the frames. The player
  # used to hold one constant for every example, which had to be kept in step
  # with the generator by hand and was not: it played back at 850ms what was
  # sampled at 280ms.
  for name <- hero_examples do
    @external_resource Path.join([hero_dir, name, "interval_ms"])
  end

  # Every ANSI frame, painted. One grid for the sequence rather than one per
  # frame: the recording's terminal does not resize mid-animation, and a pane
  # whose type rescaled between frames would jitter.
  @hero_ssh_frames Map.new(ansi_paths, fn {name, paths} ->
                     {name,
                      Enum.map(paths, fn path ->
                        path
                        |> File.read!()
                        |> SurfaceSource.ansi_rows()
                        |> SurfaceSource.ansi_html()
                      end)}
                   end)

  @hero_intervals Map.new(hero_examples, fn name ->
                    path = Path.join([hero_dir, name, "interval_ms"])

                    interval =
                      case File.read(path) do
                        {:ok, raw} ->
                          value = raw |> String.trim() |> String.to_integer()

                          # A negative tick parses fine here and reaches the
                          # browser as data-frame-ms, where
                          # `parseInt("-5", 10) || 200` is -5 -- truthy, so the
                          # fallback never fires -- and the rAF accumulator
                          # loop `while (acc >= ms) acc -= ms` grows acc
                          # forever and hangs the tab. `0` escapes only by
                          # accident, being falsy.
                          if value <= 0 do
                            raise "#{path} must be a positive integer of " <>
                                    "milliseconds, got #{value}"
                          end

                          value

                        {:error, _} ->
                          raise "#{path} is missing; rerun gen_landing_frames.exs"
                      end

                    {name, interval}
                  end)

  @hero_artifacts Map.new(surface_paths, fn {name, %{ansi: ansi, mcp: mcp}} ->
                    {name, %{ssh: File.read!(ansi), mcp: File.read!(mcp)}}
                  end)

  # Derived once: the artifacts are compile-time constants, so the line
  # breaking, clamping, escaping and colouring are too.
  @hero_surfaces Map.new(@hero_artifacts, fn {name, artifacts} ->
                   panes =
                     Map.new(artifacts, fn
                       # SSH is painted, not listed: it carries a picture, so
                       # it keeps its own grid whole and the CSS fits the type
                       # to it, exactly as the terminal pane beside it does.
                       # Frame zero only; the sequence it belongs to is built
                       # below.
                       {:ssh, artifact} ->
                         rows = SurfaceSource.ansi_rows(artifact)

                         {:ssh,
                          %{
                            html: SurfaceSource.ansi_html(rows),
                            grid: SurfaceSource.ansi_grid(rows)
                          }}

                       # MCP carries structured text a reader reads line by
                       # line, so it is broken to a line budget with a marker
                       # naming what was cut.
                       {:mcp, artifact} ->
                         clamped =
                           artifact
                           |> SurfaceSource.json_lines()
                           |> SurfaceSource.wrap()
                           |> SurfaceSource.clamp(artifact)

                         {:mcp,
                          %{
                            html: SurfaceSource.to_html(clamped, :json),
                            lines: length(clamped)
                          }}
                     end)

                   {name, panes}
                 end)

  # Previews come in two recorded shapes: a still (`<slug>.html`) and an
  # animated recording (`<slug>/frame_NN.html` + `interval_ms`, same layout
  # as the hero frames). One vocabulary out: every entry is a frame list
  # plus an interval, stills as a one-frame list with no interval.
  preview_entries = preview_dir |> File.ls!() |> Enum.sort()

  preview_stills =
    for entry <- preview_entries,
        String.ends_with?(entry, ".html"),
        do: Path.join(preview_dir, entry)

  preview_recordings =
    for entry <- preview_entries,
        dir = Path.join(preview_dir, entry),
        File.dir?(dir),
        do: {entry, dir}

  for path <- preview_stills do
    @external_resource path
  end

  for {_slug, dir} <- preview_recordings,
      path <- Path.wildcard(Path.join(dir, "*")) do
    @external_resource path
  end

  @previews Map.merge(
              Map.new(preview_stills, fn path ->
                {Path.basename(path, ".html"),
                 %{frames: [File.read!(path)], interval_ms: nil}}
              end),
              Map.new(preview_recordings, fn {slug, dir} ->
                frames =
                  dir
                  |> Path.join("frame_*.html")
                  |> Path.wildcard()
                  |> Enum.sort()
                  |> Enum.map(&File.read!/1)

                path = Path.join(dir, "interval_ms")

                interval =
                  path
                  |> File.read!()
                  |> String.trim()
                  |> String.to_integer()

                # Same trap as the hero intervals above: a negative tick hangs
                # the browser's accumulator loop rather than failing here.
                if interval <= 0 do
                  raise "#{path} must be a positive integer of milliseconds, " <>
                          "got #{interval}"
                end

                {slug, %{frames: frames, interval_ms: interval}}
              end)
            )

  @doc "Recorded frames for one hero example, in playback order."
  @spec hero_frames(String.t()) :: [String.t()]
  def hero_frames(example), do: Map.get(@hero_frames, example, [])

  @doc "Every hero example name that has recorded frames."
  @spec hero_examples() :: [String.t()]
  def hero_examples, do: @hero_frames |> Map.keys() |> Enum.sort()

  @doc """
  Milliseconds between recorded frames, which is the module's own tick.

  The page plays the recording back at the rate it was sampled at, so the
  animation runs at the speed the program actually runs.
  """
  @spec hero_frame_interval(String.t()) :: pos_integer()
  def hero_frame_interval(example), do: Map.get(@hero_intervals, example, 100)

  @doc """
  Pane markup for one hero example on one non-terminal surface, derived from
  that example's recorded artifact by `RaxolPlayground.SurfaceSource`.
  """
  @spec hero_surface(String.t(), surface()) :: String.t()
  def hero_surface(example, surface) do
    example |> pane(surface) |> Map.get(:html, "")
  end

  @doc """
  How many lines that pane holds. The CSS sizes type from this, so a short
  viewport shrinks the type rather than cutting the truncation marker.
  """
  @spec hero_surface_lines(String.t(), surface()) :: pos_integer()
  def hero_surface_lines(example, surface) do
    example |> pane(surface) |> Map.get(:lines, 1)
  end

  @doc """
  Rows and columns in the decoded SSH pane, in painted characters.

  The same two-axis fit the terminal frames get: the recording's grid is fixed
  and the pane's is not, so the type follows the frame rather than the frame
  being cut to a line budget it never fit.
  """
  @spec hero_ssh_grid(String.t()) :: %{rows: pos_integer(), cols: pos_integer()}
  def hero_ssh_grid(example) do
    example |> pane(:ssh) |> Map.get(:grid, %{rows: 1, cols: 1})
  end

  @doc """
  Painted markup for every recorded ANSI frame, in playback order.

  One per terminal frame, so the two panes step together: the same buffer, on
  two surfaces, at the same moment.
  """
  @spec hero_ssh_frames(String.t()) :: [String.t()]
  def hero_ssh_frames(example), do: Map.get(@hero_ssh_frames, example, [])

  defp pane(example, surface) do
    @hero_surfaces |> Map.get(example, %{}) |> Map.get(surface, %{})
  end

  @doc """
  Rows and columns in one recorded terminal frame.

  The CSS sizes the frame's type from both, so the frame grows to fill the
  pane it is given and shrinks to fit a short one, instead of sitting at a
  fixed size with dead space beside it.
  """
  @spec hero_frame_grid(String.t()) :: %{
          rows: pos_integer(),
          cols: pos_integer()
        }
  def hero_frame_grid(example) do
    case hero_frames(example) do
      [frame | _] -> grid(frame)
      [] -> %{rows: 1, cols: 1}
    end
  end

  # Measured off the frame's own text: the recording geometry lives in the
  # generator, and a second copy of it here would be free to drift.
  defp grid(frame) do
    lines =
      frame
      |> String.replace(~r/<[^>]*>/, "")
      |> unescape()
      |> String.split("\n")
      # The encoder closes with a newline before `</pre>`, so the last split is
      # the closing tag rather than a row.
      |> Enum.drop(-1)

    %{
      rows: max(length(lines), 1),
      cols:
        lines |> Enum.map(&String.length/1) |> Enum.max(fn -> 1 end) |> max(1)
    }
  end

  defp unescape(text) do
    # &amp; last, or an escaped &amp;lt; would come back as a literal <.
    text
    |> String.replace("&lt;", "<")
    |> String.replace("&gt;", ">")
    |> String.replace("&quot;", "\"")
    |> String.replace("&#39;", "'")
    |> String.replace("&amp;", "&")
  end

  @doc """
  The recorded artifact a pane was derived from, verbatim. Exposed so a test
  can check every line the pane shows against it.
  """
  @spec hero_artifact(String.t(), surface()) :: String.t()
  def hero_artifact(example, surface) do
    @hero_artifacts |> Map.get(example, %{}) |> Map.get(surface, "")
  end

  @typedoc """
  A hero surface with an artifact of its own.

  The terminal and browser panes both play `hero_frames/1` and so appear here
  under neither name.
  """
  @type surface :: :ssh | :mcp

  @doc """
  Recorded preview for a catalog demo name, or nil.

  `%{frames: [html], interval_ms: nil}` for a still, `%{frames: [...],
  interval_ms: ms}` for an animated demo's recording, played back at the
  demo's own tick.
  """
  @spec preview(String.t()) ::
          %{frames: [String.t()], interval_ms: pos_integer() | nil} | nil
  def preview(name), do: Map.get(@previews, slug(name))

  @doc "The slug a demo name is stored under (mirrors the generator)."
  @spec slug(String.t()) :: String.t()
  def slug(name) do
    name
    |> String.downcase()
    |> String.replace(~r/[^a-z0-9]+/, "_")
    |> String.trim("_")
  end
end
