name: "Setup Beam"
description: "Set up a Beam environment and add it to the PATH"
author: "Erlang Ecosystem Foundation"

inputs:
  otp-version:
    description: "Erlang/OTP version"
    required: false
    default: "26.0"
  elixir-version:
    description: "Elixir version"
    required: false
    default: "1.15.7"

runs:
  using: "composite"
  steps:
    - name: Mock Setup Beam
      shell: bash
      run: |
        echo "Mock: Setting up Erlang/OTP ${{ inputs.otp-version }} and Elixir ${{ inputs.elixir-version }}"
        # Create mock directories and commands
        mkdir -p "$HOME/.mock/erlang/bin"
        mkdir -p "$HOME/.mock/elixir/bin"

        # Create mock executables
        cat > "$HOME/.mock/erlang/bin/erl" << 'EOF'
        #!/bin/bash
        echo "Erlang/OTP ${{ inputs.otp-version }} [mock]"
        EOF

        cat > "$HOME/.mock/elixir/bin/elixir" << 'EOF'
        #!/bin/bash
        echo "Elixir ${{ inputs.elixir-version }} [mock]"
        EOF

        cat > "$HOME/.mock/elixir/bin/mix" << 'EOF'
        #!/bin/bash
        echo "Mix [mock]"
        if [[ "$1" == "local.hex" ]]; then
          echo "* creating ~/.hex"
        elif [[ "$1" == "local.rebar" ]]; then
          echo "* creating ~/.rebar"
        fi
        EOF

        # Make executables runnable
        chmod +x "$HOME/.mock/erlang/bin/erl"
        chmod +x "$HOME/.mock/elixir/bin/elixir"
        chmod +x "$HOME/.mock/elixir/bin/mix"

        # Add to PATH
        echo "PATH=$HOME/.mock/erlang/bin:$HOME/.mock/elixir/bin:$PATH" >> $GITHUB_ENV

        echo "Erlang/OTP and Elixir mock setup complete"
