name: 'Setup Development Environment'
description: 'Set up Elixir, OTP, optionally Node.js, and restore caches'

inputs:
  elixir-version:
    description: 'Elixir version to install'
    required: false
    default: '1.17.3'
  otp-version:
    description: 'OTP version to install'
    required: false
    default: '27.0'
  cache-key:
    description: 'Cache key for dependencies'
    required: false
    default: ''
  install-deps:
    description: 'Whether to install dependencies'
    required: false
    default: 'true'
  use-container:
    description: 'Use Docker container for CI'
    required: false
    default: 'false'
  node-version:
    description: 'Node.js version to install (leave empty to skip Node.js setup)'
    required: false
    default: ''
  node-cache:
    description: 'Package manager to cache Node.js dependencies'
    required: false
    default: 'npm'
  node-cache-dependency-path:
    description: 'Path to package-lock.json or yarn.lock file'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Setup Elixir (native)
      if: inputs.use-container == 'false'
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{ inputs.elixir-version }}
        otp-version: ${{ inputs.otp-version }}
    
    - name: Cache dependencies
      if: inputs.cache-key != ''
      uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
      with:
        path: |
          deps
          _build
          .raxol_cache
          priv/plts
          ~/.hex
          ~/.mix
        key: ${{ inputs.cache-key }}
        restore-keys: |
          deps-${{ runner.os }}-${{ inputs.otp-version }}-${{ inputs.elixir-version }}-
          deps-${{ runner.os }}-
    
    - name: Install Hex and Rebar
      if: inputs.use-container == 'false'
      shell: bash
      run: |
        mix local.hex --force
        mix local.rebar --force
    
    - name: Setup Node.js
      if: inputs.node-version != ''
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: ${{ inputs.node-cache }}
        cache-dependency-path: ${{ inputs.node-cache-dependency-path }}

    - name: Install dependencies
      if: inputs.install-deps == 'true'
      shell: bash
      run: |
        mix deps.get
        mix deps.compile
      env:
        MIX_ENV: test