version: "3.8"

services:
  postgres:
    image: postgres:15
    platform: linux/arm64 # Optimized for M-series Macs
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: raxol_test
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  elixir:
    image: elixir-arm64:latest
    platform: linux/arm64
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/workspace
    working_dir: /workspace
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: raxol_test
      MIX_ENV: test
      TERM: xterm-256color
