FROM elixir:1.20.3-otp-29@sha256:5159e0bdb2c43dbb0fabc9385c20a236e2e1ad88c32d1b6cc6985e3008739be3

# Install basic dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
  build-essential \
  autoconf \
  m4 \
  libncurses5-dev \
  libssl-dev \
  libgl1-mesa-dev \
  libglu1-mesa-dev \
  libpng-dev \
  openssl \
  git \
  curl \
  wget \
  unzip \
  nodejs \
  npm \
  yarn \
  && rm -rf /var/lib/apt/lists/*

# Set up environment
ENV MIX_HOME=/root/.mix
ENV HEX_HOME=/root/.hex

# Install Hex and Rebar
RUN mix local.hex --force && \
  mix local.rebar --force

WORKDIR /app

CMD ["tail", "-f", "/dev/null"]
