defmodule Raxol.UI.Theming.Palette do
  @moduledoc """
  Single canonical home for Raxol's palette PRIMITIVES: the color VALUES that
  theming, terminal rendering, and UI components pull from -- as opposed to
  the color-manipulation ALGORITHMS (HSL conversion, harmony, gradients,
  accessibility suggestion, contrast calculation), which stay where they are
  (`Raxol.Style.Colors.*`, `Raxol.UI.Theming.Salience`).

  ## Why this module exists

  A full-codebase audit (`docs/proposals/palette-inventory.md`)
  found the same conceptual color defined independently, with DIFFERENT
  values, in many places -- most strikingly at least four conflicting "the
  standard ANSI 16 colors" conventions (6+ literal copies) and at least five
  unrelated "the default semantic theme" token sets. This module does not
  silently pick a winner (that would change runtime behaviour for whichever
  call sites are later pointed at it) -- it PRESERVES every existing value
  under a clearly attributed name, so future migration work can make an
  informed choice call site by call site. See the inventory doc for the full
  duplicate/conflict catalogue, file:line citations, and a ranked list of the
  call sites most worth migrating.

  Migration has started. Consuming this module today: `Raxol.UI.CellDim`,
  `Raxol.UI.ColorResolver`, `Raxol.Core.Renderer.Color`,
  `Raxol.Core.Renderer.View.Utils.ViewUtils`,
  `Raxol.Effects.BorderBeam.Colors` and
  `Raxol.UI.Components.Harness.DiffViewer`. The ANSI-16 name->slot map, the
  unknown-atom fallback, the BorderBeam variant tables and the diff tiers no
  longer exist as private copies anywhere. Remaining un-migrated conflicts
  (hex/RGB conversion with contradictory error contracts, the semantic-token
  sets) still keep their own copies, and each needs a behaviour decision
  before it can be pointed here.

  Note that box-drawing glyphs are deliberately NOT here: this module is
  color values. They live in `Raxol.UI.Theming.BorderChars`.

  ## Sections

    * Named colors -- CSS-ish web color names, merged from the two sources
      that agreed with each other byte-for-byte.
    * WCAG-safe fallbacks -- black/white, duplicated ~15x verbatim elsewhere.
    * The near-black surface convention -- `#1E1E1E`, duplicated 3x elsewhere.
    * ANSI 16 basic palette -- 4 documented, mutually conflicting variants.
    * ANSI 256 cube / grayscale -- generation constants; 2 conflicting cube
      formulas, 1 uncontested grayscale ramp.
    * Platform terminal palettes -- linux/mac/windows, uncontested.
    * Semantic default-theme families -- 7 conflicting token sets, each
      preserved exactly under the name of the module it came from.
    * Salience / H-K tier anchors -- delegates to the live source
      (`Raxol.UI.Theming.SalienceTheme`) rather than copying literals, so it
      can never drift. The darcula-family reference bake is a byte-exact
      test fixture in `test/raxol/ui/theming/salience_test.exs` and is
      deliberately NOT reproduced here -- it is generated by
      `Salience.solve/3`'s floating-point math, not stored as a literal.
    * Effect accent palettes -- BorderBeam's 7 variants (ANSI + CSS flavors).

  ## Non-goals

  This module does not implement color conversion, blending, contrast
  calculation, or theme resolution -- see `Raxol.Style.Colors.Color`,
  `Raxol.Style.Colors.Formats`, `Raxol.Style.Colors.Utilities`,
  `Raxol.UI.Theming.Theme`, and `Raxol.Core.Theming.ThemeRegistry` for those.
  It also does not attempt to catalog the 10 named community themes already
  well-organized in `Raxol.Core.Theming.ThemeRegistry` (dracula, nord,
  monokai, gruvbox, solarized, tokyo_night, one_dark, catppuccin,
  synthwave84) -- that module already serves that role; duplicating it here
  would just add a fifth copy to a category that already has too many.
  """

  alias Raxol.UI.Theming.Salience
  alias Raxol.UI.Theming.SalienceTheme

  @type hex :: String.t()
  @type rgb :: {0..255, 0..255, 0..255}
  @type ansi_16_variant :: :xterm | :vga | :gnome_terminal | :pure_pastel
  @type ansi_256_cube_formula :: :xterm_accurate | :naive_linear
  @type platform :: :linux | :mac | :windows
  @type semantic_family ::
          :dracula_ide
          | :dracula_ide_dark
          | :brand_light
          | :material_dark
          | :material_high_contrast
          | :web_tailwind
          | :web_bootstrap
          | :renderer_defaults
  @type border_beam_variant ::
          :colorful | :mono | :ocean | :sunset | :electric | :neon | :matrix

  # ===========================================================================
  # Named colors
  # ===========================================================================
  # Merges two sources that were found to agree byte-for-byte on every
  # overlapping name: Raxol.UI.Theming.Colors's private @color_names
  # (lib/raxol/ui/theming/colors.ex:28-44 -- that module has no public
  # accessor for the raw map, only per-name lookups via to_hex/1 / to_rgb/1)
  # and Raxol.Terminal.Color.TrueColor.Palette's @colors
  # (packages/raxol_terminal/lib/raxol/terminal/color/true_color/palette.ex:6-25,
  # RGB-tuple flavored there). Where both defined a name, the values matched
  # exactly, so this is a lossless superset, not a conflict resolution.

  @named_colors %{
    black: "#000000",
    white: "#FFFFFF",
    red: "#FF0000",
    green: "#00FF00",
    blue: "#0000FF",
    yellow: "#FFFF00",
    cyan: "#00FFFF",
    magenta: "#FF00FF",
    gray: "#808080",
    lightgray: "#D3D3D3",
    darkgray: "#A9A9A9",
    purple: "#800080",
    orange: "#FFA500",
    pink: "#FFC0CB",
    brown: "#A52A2A",
    # From Raxol.Terminal.Color.TrueColor.Palette (no conflict, net-new names)
    lime: "#00FF00",
    navy: "#000080",
    olive: "#808000",
    silver: "#C0C0C0",
    teal: "#008080"
  }

  @doc "All named colors as a name => hex map."
  @spec named_colors() :: %{atom() => hex()}
  def named_colors, do: @named_colors

  @doc "Looks up one named color. Returns `nil` for an unknown name."
  @spec named_color(atom()) :: hex() | nil
  def named_color(name) when is_atom(name), do: Map.get(@named_colors, name)

  # ===========================================================================
  # WCAG-safe fallbacks
  # ===========================================================================
  # The literal pair "#000000"/"#FFFFFF" recurs as an independent hardcoded
  # "safe" fallback 15+ times across the codebase (utilities.ex, suggester.ex
  # x10, color_system_server.ex, palette_generator.ex, theme.ex, selector.ex,
  # theme_implementations.ex, theme_resolver.ex -- see inventory §5.7).

  @doc "The WCAG-safe black fallback, as reused independently 15+ times across the codebase."
  @spec black() :: hex()
  def black, do: "#000000"

  @doc "The WCAG-safe white fallback, as reused independently 15+ times across the codebase."
  @spec white() :: hex()
  def white, do: "#FFFFFF"

  # ===========================================================================
  # The near-black surface convention
  # ===========================================================================
  # "#1E1E1E" / rgb(30,30,30) recurs independently in three unrelated files,
  # currently in sync by luck rather than by shared source (inventory §5.2):
  # Theme.default_theme/0's :surface token, Modal.Rendering's @default_surface
  # fallback, and ThemeIntegration's :standard-mode background.

  @doc "The near-black surface value shared (independently) by three unrelated call sites."
  @spec near_black_surface() :: hex()
  def near_black_surface, do: "#1E1E1E"

  @doc "Same value as `near_black_surface/0`, as the RGB tuple form used by `theme_integration.ex`."
  @spec near_black_surface_rgb() :: rgb()
  def near_black_surface_rgb, do: {30, 30, 30}

  # ===========================================================================
  # ANSI 16 basic palette -- FOUR conflicting conventions in the wild
  # ===========================================================================
  # See inventory §5.1 for the full side-by-side table and every source file.
  # All four variants are normalized to `[rgb()]` here (the GNOME/Ubuntu
  # source is natively hex; each entry below carries its source hex in a
  # comment so it can be spot-checked without doing the hex math yourself).

  @ansi_16_names [
    :black,
    :red,
    :green,
    :yellow,
    :blue,
    :magenta,
    :cyan,
    :white,
    :bright_black,
    :bright_red,
    :bright_green,
    :bright_yellow,
    :bright_blue,
    :bright_magenta,
    :bright_cyan,
    :bright_white
  ]

  @doc "The 16 ANSI color names in SGR 30-37/90-97 order, shared by every `ansi_16/1` variant."
  @spec ansi_16_names() :: [atom()]
  def ansi_16_names, do: @ansi_16_names

  # Derived from @ansi_16_names rather than written out again: the name list
  # already fixes the SGR order, so a second literal could only drift from it.
  @ansi_16_codes @ansi_16_names |> Enum.with_index() |> Map.new()

  @doc """
  ANSI-16 color name -> SGR slot (0-15).

  Replaces four private copies of this map, in
  `Raxol.Core.Renderer.Color`, `Raxol.Core.Renderer.View.Utils.ViewUtils`,
  `Raxol.UI.CellDim` and `Raxol.UI.ColorResolver`. Two of those carried a
  comment arguing that "a small, stable, private lookup beats a cross-module
  dependency on a private attribute" -- true while this module did not exist,
  and the ViewUtils copy had decayed into a 16-entry map rebuilt on every
  call from a render-path helper.
  """
  @spec ansi_16_codes() :: %{atom() => 0..15}
  def ansi_16_codes, do: @ansi_16_codes

  @doc """
  Slot -> ANSI-16 color name, the inverse of `ansi_16_codes/0`.
  """
  @spec ansi_16_slots() :: %{(0..15) => atom()}
  def ansi_16_slots,
    do: Map.new(@ansi_16_codes, fn {name, code} -> {code, name} end)

  @doc """
  Mid-gray, for a color atom outside the ANSI-16 set (`:default`,
  theme-custom names). Shared by `CellDim` and `ColorResolver`, which each
  held their own `@unknown_atom_rgb` with this value: an unknown atom still
  has to take the dim/fade cue, so it needs *some* RGB rather than `nil`.
  """
  @spec unknown_atom_rgb() :: rgb()
  def unknown_atom_rgb, do: {128, 128, 128}

  # xterm convention. Matches (byte-for-byte, as of this audit):
  #   Raxol.Style.Colors.Formats.basic_ansi_color/1
  #   Raxol.Style.Colors.Color.to_ansi_16/1 (inline list)
  #   Raxol.Terminal.Color.Manager.default_palette
  #   Raxol.Terminal.ANSI.SixelPalette.initialize_base_palette/0
  @ansi_16_xterm [
    {0, 0, 0},
    {205, 0, 0},
    {0, 205, 0},
    {205, 205, 0},
    {0, 0, 238},
    {205, 0, 205},
    {0, 205, 205},
    {229, 229, 229},
    {127, 127, 127},
    {255, 0, 0},
    {0, 255, 0},
    {255, 255, 0},
    {92, 92, 255},
    {255, 0, 255},
    {0, 255, 255},
    {255, 255, 255}
  ]

  # VGA/half-intensity convention. Matches Raxol.UI.Theming.Colors.@ansi_basic_colors
  # and (independently) packages/raxol_liveview's terminal_bridge.ex @ansi_16.
  @ansi_16_vga [
    {0, 0, 0},
    {128, 0, 0},
    {0, 128, 0},
    {128, 128, 0},
    {0, 0, 128},
    {128, 0, 128},
    {0, 128, 128},
    {192, 192, 192},
    {128, 128, 128},
    {255, 0, 0},
    {0, 255, 0},
    {255, 255, 0},
    {0, 0, 255},
    {255, 0, 255},
    {0, 255, 255},
    {255, 255, 255}
  ]

  # GNOME/Ubuntu Terminal convention (the classic "Tango" palette).
  @ansi_16_gnome_terminal [
    # black          #000000
    {0, 0, 0},
    # red            #cc0000
    {204, 0, 0},
    # green          #4e9a06
    {78, 154, 6},
    # yellow         #c4a000
    {196, 160, 0},
    # blue           #3465a4
    {52, 101, 164},
    # magenta        #75507b
    {117, 80, 123},
    # cyan           #06989a
    {6, 152, 154},
    # white          #d3d7cf
    {211, 215, 207},
    # bright_black   #555753
    {85, 87, 83},
    # bright_red     #ef2929
    {239, 41, 41},
    # bright_green   #8ae234
    {138, 226, 52},
    # bright_yellow  #fce94f
    {252, 233, 79},
    # bright_blue    #729fcf
    {114, 159, 207},
    # bright_magenta #ad7fa8
    {173, 127, 168},
    # bright_cyan    #34e2e2
    {52, 226, 226},
    # bright_white   #eeeeec
    {238, 238, 236}
  ]

  # Pure-saturated base + 50%-toward-white bright variants. Matches (byte-for
  # byte) both Raxol.LiveView.Themes.@themes.default (hex flavor) and
  # Raxol.Terminal.Theme.Manager.new/1's hardcoded default (RGBA flavor) --
  # two independent files that landed on identical values.
  @ansi_16_pure_pastel [
    {0, 0, 0},
    {255, 0, 0},
    {0, 255, 0},
    {255, 255, 0},
    {0, 0, 255},
    {255, 0, 255},
    {0, 255, 255},
    {255, 255, 255},
    {128, 128, 128},
    {255, 128, 128},
    {128, 255, 128},
    {255, 255, 128},
    {128, 128, 255},
    {255, 128, 255},
    {128, 255, 255},
    {255, 255, 255}
  ]

  @doc """
  Returns one of the 4 conflicting ANSI 16-color conventions found in the
  codebase, as a 16-element list of `{r, g, b}` tuples in `ansi_16_names/0`
  order. Defaults to `:xterm`, the convention with the most independent
  copies. See inventory §5.1 for the full comparison table.
  """
  @spec ansi_16(ansi_16_variant()) :: [rgb()]
  def ansi_16(variant \\ :xterm)
  def ansi_16(:xterm), do: @ansi_16_xterm
  def ansi_16(:vga), do: @ansi_16_vga
  def ansi_16(:gnome_terminal), do: @ansi_16_gnome_terminal
  def ansi_16(:pure_pastel), do: @ansi_16_pure_pastel

  @doc "The known ANSI 16-color convention variant names, for iteration/tests."
  @spec ansi_16_variants() :: [ansi_16_variant()]
  def ansi_16_variants, do: [:xterm, :vga, :gnome_terminal, :pure_pastel]

  @doc "Like `ansi_16/1`, but keyed by color name instead of positional index."
  @spec ansi_16_named(ansi_16_variant()) :: %{atom() => rgb()}
  def ansi_16_named(variant \\ :xterm) do
    @ansi_16_names |> Enum.zip(ansi_16(variant)) |> Map.new()
  end

  # ===========================================================================
  # ANSI 256 cube (16-231) and grayscale ramp (232-255)
  # ===========================================================================
  # The 216-color cube has two competing step formulas in the codebase (see
  # inventory §5.1). :xterm_accurate (0,95,135,175,215,255) is the real xterm
  # 256-color formula, from Raxol.UI.Theming.Colors.@ansi_216_colors.
  # :naive_linear (0,51,102,153,204,255) is what
  # Raxol.Style.Colors.Formats.ansi_to_rgb/1 and
  # Raxol.Terminal.ANSI.SixelPalette both actually use -- preserved here
  # under its own name rather than silently "fixed", since a caller may
  # depend on its current (inaccurate but consistent) output.

  @spec cube_level(:xterm_accurate, 0..5) :: 0..255
  defp cube_level(:xterm_accurate, 0), do: 0
  defp cube_level(:xterm_accurate, n), do: 55 + n * 40
  defp cube_level(:naive_linear, n), do: n * 51

  @doc """
  Generates the 216-entry ANSI 256-color cube (indices 16-231) under the
  given step formula. Returns `[{index, {r, g, b}}]`.
  """
  @spec ansi_256_cube(ansi_256_cube_formula()) :: [{16..231, rgb()}]
  def ansi_256_cube(formula) when formula in [:xterm_accurate, :naive_linear] do
    for r <- 0..5, g <- 0..5, b <- 0..5 do
      index = 16 + 36 * r + 6 * g + b

      {index,
       {cube_level(formula, r), cube_level(formula, g), cube_level(formula, b)}}
    end
  end

  @doc """
  Generates the 24-entry ANSI 256-color grayscale ramp (indices 232-255).
  Returns `[{index, {level, level, level}}]`. Unlike the cube, every source
  in the codebase agrees on this formula -- there is only one variant.
  """
  @spec ansi_256_grayscale() :: [{232..255, rgb()}]
  def ansi_256_grayscale do
    for i <- 0..23 do
      level = 8 + i * 10
      {232 + i, {level, level, level}}
    end
  end

  # ===========================================================================
  # Platform terminal palettes (uncontested)
  # ===========================================================================
  # Mirrors Raxol.UI.Theming.Colors's private @linux_colors / @mac_colors /
  # @windows_colors (lib/raxol/ui/theming/colors.ex:458-516). No other module
  # in the audit defines an equivalent platform-specific 16-color table, so
  # there is nothing to conflict with -- these are transcribed verbatim.

  @linux_colors [
    {0, {0, 0, 0}},
    {1, {170, 0, 0}},
    {2, {0, 170, 0}},
    {3, {170, 85, 0}},
    {4, {0, 0, 170}},
    {5, {170, 0, 170}},
    {6, {0, 170, 170}},
    {7, {170, 170, 170}},
    {8, {85, 85, 85}},
    {9, {255, 85, 85}},
    {10, {85, 255, 85}},
    {11, {255, 255, 85}},
    {12, {85, 85, 255}},
    {13, {255, 85, 255}},
    {14, {85, 255, 255}},
    {15, {255, 255, 255}}
  ]

  @mac_colors [
    {0, {0, 0, 0}},
    {1, {194, 54, 33}},
    {2, {37, 188, 36}},
    {3, {173, 173, 39}},
    {4, {73, 46, 225}},
    {5, {211, 56, 211}},
    {6, {51, 187, 200}},
    {7, {203, 204, 205}},
    {8, {129, 131, 131}},
    {9, {252, 57, 31}},
    {10, {49, 231, 34}},
    {11, {234, 236, 35}},
    {12, {88, 51, 255}},
    {13, {249, 53, 248}},
    {14, {20, 240, 240}},
    {15, {233, 235, 235}}
  ]

  @windows_colors [
    {0, {12, 12, 12}},
    {1, {197, 15, 31}},
    {2, {19, 161, 14}},
    {3, {193, 156, 0}},
    {4, {0, 55, 218}},
    {5, {136, 23, 152}},
    {6, {58, 150, 221}},
    {7, {204, 204, 204}},
    {8, {118, 118, 118}},
    {9, {231, 72, 86}},
    {10, {22, 198, 12}},
    {11, {249, 241, 165}},
    {12, {59, 120, 255}},
    {13, {180, 0, 158}},
    {14, {97, 214, 214}},
    {15, {242, 242, 242}}
  ]

  @doc """
  Returns the platform-flavored 16-color terminal palette as
  `[{index, {r, g, b}}]`, matching each OS's real terminal default colors
  (as opposed to any of the `ansi_16/1` conventions, which are all
  synthetic/idealized).
  """
  @spec platform_palette(platform()) :: [{0..15, rgb()}]
  def platform_palette(:linux), do: @linux_colors
  def platform_palette(:mac), do: @mac_colors
  def platform_palette(:windows), do: @windows_colors

  # ===========================================================================
  # Semantic default-theme families -- SEVEN conflicting token sets
  # ===========================================================================
  # See inventory §1 for full provenance and §5.4/§5.5 for the cross-family
  # comparisons. Each family is preserved EXACTLY as found -- do not "fix"
  # any of these to match another; each is independently pinned by its own
  # call sites (several by tests) and picking a winner is a product decision
  # deliberately left to a future, separate PR.

  @doc """
  Returns one of the 7 independently-defined "default semantic theme" token
  sets found in the codebase, exactly as defined at its source. Token keys
  and even the *set* of tokens differ between families by design -- these
  are not meant to be interchangeable, only auditable side by side.
  """
  @spec semantic_defaults(semantic_family()) :: %{atom() => hex()}
  # Raxol.UI.Theming.Theme.default_theme/0 -- lib/raxol/ui/theming/theme.ex:183-238
  def semantic_defaults(:dracula_ide) do
    %{
      background: "#000000",
      surface: "#1E1E1E",
      foreground: "#FFFFFF",
      accent: "#4A9CD5",
      error: "#FF5555",
      warning: "#FFB86C",
      success: "#50FA7B",
      fuschia: "#FF00FF"
    }
  end

  # Raxol.UI.Theming.Theme.dark_theme/0 -- lib/raxol/ui/theming/theme.ex:243-277
  def semantic_defaults(:dracula_ide_dark) do
    %{
      background: "#1E1E1E",
      foreground: "#FFFFFF",
      accent: "#4A9CD5",
      error: "#FF5555",
      warning: "#FFB86C",
      success: "#50FA7B",
      fuschia: "#FF00FF"
    }
  end

  # Raxol.UI.Theming.Theme.new/0 via private default_attrs/0 --
  # lib/raxol/ui/theming/theme.ex:306-363
  def semantic_defaults(:brand_light) do
    %{
      primary: "#0077CC",
      secondary: "#666666",
      accent: "#FF9900",
      background: "#FFFFFF",
      surface: "#F5F5F5",
      error: "#CC0000",
      success: "#009900",
      warning: "#FF9900",
      info: "#0099CC",
      text: "#000000",
      foreground: "#000000"
    }
  end

  # Raxol.Style.Colors.System.create_dark_theme/0 -- lib/raxol/style/colors/system.ex:233-251
  def semantic_defaults(:material_dark) do
    %{
      primary: "#90CAF9",
      secondary: "#B0BEC5",
      background: "#121212",
      text: "#FFFFFF"
    }
  end

  # Raxol.Style.Colors.System.create_high_contrast_theme/0 -- lib/raxol/style/colors/system.ex:253-271
  def semantic_defaults(:material_high_contrast) do
    %{
      primary: "#FFFF00",
      secondary: "#000000",
      background: "#000000",
      text: "#FFFFFF"
    }
  end

  # lib/raxol/ui/universal.ex:66-91 -- matches Tailwind CSS v3 defaults
  def semantic_defaults(:web_tailwind) do
    %{
      primary: "#2563eb",
      secondary: "#6b7280",
      success: "#10b981",
      warning: "#f59e0b",
      error: "#ef4444",
      background: "#ffffff",
      surface: "#f9fafb",
      text: "#111827",
      text_muted: "#6b7280"
    }
  end

  # lib/raxol/ui/state/context.ex:354-379 -- success/warning/error match Bootstrap 4
  def semantic_defaults(:web_bootstrap) do
    %{
      primary: "#007acc",
      secondary: "#6c757d",
      success: "#28a745",
      warning: "#ffc107",
      error: "#dc3545",
      background: "#ffffff",
      surface: "#f8f9fa",
      text: "#212529"
    }
  end

  @doc "RGB-tuple-flavored sibling of `semantic_defaults/1` for the one family stored that way."
  @spec renderer_defaults() :: %{atom() => rgb()}
  # Raxol.Core.Renderer.Color.merge_with_defaults/1 -- lib/raxol/core/renderer/color.ex:249-260
  def renderer_defaults do
    %{
      foreground: {0, 0, 0},
      background: {255, 255, 255},
      primary: {0, 119, 204},
      secondary: {102, 102, 102},
      accent: {255, 153, 0},
      error: {204, 0, 0},
      warning: {255, 153, 0},
      success: {0, 153, 0},
      surface: {245, 245, 245},
      text: {51, 51, 51},
      info: {0, 153, 204}
    }
  end

  @doc "The known semantic-default family names, for iteration/tests."
  @spec semantic_default_families() :: [semantic_family()]
  def semantic_default_families do
    [
      :dracula_ide,
      :dracula_ide_dark,
      :brand_light,
      :material_dark,
      :material_high_contrast,
      :web_tailwind,
      :web_bootstrap
    ]
  end

  # ===========================================================================
  # Salience / H-K tier anchors -- delegated, not copied
  # ===========================================================================
  # These delegate directly to the live source rather than mirroring literals,
  # so they can never silently drift out of sync with the solver they
  # describe. The darcula-family reference bake
  # (test/raxol/ui/theming/salience_test.exs's @darcula_baked, 16 entries,
  # plus salience_theme_test.exs's 4 semantic checks) is generated by
  # Salience.solve/3's floating-point math and is NOT reproduced here -- it
  # is a byte-exact test fixture; touching it breaks tests for no benefit,
  # since the "constant" it pins IS the solver's output, not a stored value.

  @doc """
  The semantic `(name, hue, chroma, tier)` seed table the salience/H-K color
  system solves against a ground lightness. Delegates to
  `Raxol.UI.Theming.SalienceTheme.seeds/0` (not copied) so this can never
  drift from the live source.
  """
  @spec salience_darcula_seeds() :: [map()]
  defdelegate salience_darcula_seeds(), to: SalienceTheme, as: :seeds

  @doc """
  The reference near-black ground OKLCH lightness the salience tier deltas
  were derived against. Delegates to
  `Raxol.UI.Theming.Salience.reference_ground/0` (not copied).
  """
  @spec salience_reference_ground() :: float()
  defdelegate salience_reference_ground(), to: Salience, as: :reference_ground

  # ===========================================================================
  # Effect accent palettes -- BorderBeam (explicitly in scope)
  # ===========================================================================
  # lib/raxol/effects/border_beam/colors.ex encodes each of its 7 variants
  # twice: once as ANSI atoms (terminal path), once as CSS hex (LiveView/web
  # path). The two encodings are independently maintained art direction, not
  # mechanically derived from each other -- both preserved verbatim.

  @border_beam_palettes %{
    colorful: [
      :bright_red,
      :bright_yellow,
      :bright_green,
      :bright_cyan,
      :bright_blue,
      :bright_magenta
    ],
    mono: [:bright_white, :white, :bright_black],
    ocean: [:bright_cyan, :cyan, :bright_blue, :blue],
    sunset: [:bright_yellow, :yellow, :bright_red, :red],
    electric: [:bright_yellow, :bright_cyan, :bright_white, :cyan],
    neon: [:bright_magenta, :bright_cyan, :magenta, :bright_blue],
    matrix: [:bright_green, :green, :bright_black]
  }

  @border_beam_css_palettes %{
    colorful: ["#ff0040", "#ffaa00", "#00ff88", "#00ccff", "#4400ff", "#ff00cc"],
    mono: ["#ffffff", "#cccccc", "#999999"],
    ocean: ["#0044ff", "#00ccff", "#0077ff", "#00aaff"],
    sunset: ["#ff4400", "#ffaa00", "#ff6600", "#ffcc00"],
    electric: ["#fff700", "#00ffff", "#ffffff", "#00d4ff"],
    neon: ["#ff00ff", "#00ffff", "#ff00cc", "#7700ff"],
    matrix: ["#00ff66", "#00cc44", "#006622", "#003311"]
  }

  @border_beam_glow_colors %{
    colorful: :blue,
    mono: :white,
    ocean: :blue,
    sunset: :red,
    electric: :yellow,
    neon: :magenta,
    matrix: :green
  }

  @border_beam_bloom_colors %{
    colorful: :magenta,
    mono: :white,
    ocean: :cyan,
    sunset: :yellow,
    electric: :cyan,
    neon: :cyan,
    matrix: :green
  }

  @doc "The BorderBeam effect's ANSI-atom accent palette for a variant (terminal rendering path)."
  @spec effect_palette(:border_beam, border_beam_variant()) :: [atom()]
  def effect_palette(:border_beam, variant),
    do: Map.fetch!(@border_beam_palettes, variant)

  @doc "The BorderBeam effect's CSS hex accent palette for a variant (LiveView/web rendering path)."
  @spec effect_palette_css(:border_beam, border_beam_variant()) :: [hex()]
  def effect_palette_css(:border_beam, variant),
    do: Map.fetch!(@border_beam_css_palettes, variant)

  @doc "The BorderBeam effect's muted inner-glow accent color for a variant."
  @spec effect_accent(:border_beam, :glow | :bloom, border_beam_variant()) ::
          atom()
  def effect_accent(:border_beam, :glow, variant),
    do: Map.fetch!(@border_beam_glow_colors, variant)

  def effect_accent(:border_beam, :bloom, variant),
    do: Map.fetch!(@border_beam_bloom_colors, variant)

  # ===========================================================================
  # Diff visual language (harness DiffViewer / DiffExpansion)
  # ===========================================================================
  # Pre-flattened opaque bg/fg tiers approximating layered translucent diff
  # backgrounds against a dark terminal ground: a row wash, a brighter
  # intra-line-emphasis tier over it, and a weaker gutter tint. Terminal
  # cells carry one bg and one fg, so the translucency is flattened to these
  # discrete tiers rather than composited.
  #
  # Previously `@diff_palette` in
  # `Raxol.UI.Components.Harness.DiffViewer`, behind a TODO to "consolidate
  # with the project-wide palette inventory ... once it exists". The
  # inventory doc exists at neither of the two paths the codebase cites, so
  # that TODO would never have fired; consolidating here is what it asked
  # for.
  @diff_palette %{
    add_base: "#5ECC71",
    add_row_bg: "#12261B",
    add_emphasis_bg: "#1D4428",
    add_gutter_bg: "#0F1D16",
    del_base: "#FF6762",
    del_row_bg: "#291418",
    del_emphasis_bg: "#552527",
    del_gutter_bg: "#200F12"
  }

  @doc """
  The diff visual language's hex tiers: `add_base`, `add_row_bg`,
  `add_emphasis_bg`, `add_gutter_bg` and their `del_*` counterparts.
  """
  @spec diff_palette() :: %{atom() => hex()}
  def diff_palette, do: @diff_palette
end
