name: CI-Local-Dependencies

on:
  workflow_dispatch:

jobs:
  test-deps:
    name: Test Ranch Dependency
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Mix and Rebar
        run: |
          echo "Elixir version: $(elixir --version)"
          mix local.hex --force
          mix local.rebar --force

      - name: Install Mix Dependencies with improved error handling
        run: |
          # Set environment variables for verbose output
          export DIAGNOSTIC=1
          export ERL_COMPILER_OPTIONS=bin_opt_info

          # Get dependencies
          mix deps.get

          # Handle problematic dependencies
          echo "Explicitly compiling ranch with --force"
          mix deps.compile ranch --force

          # Compile other dependencies
          mix deps.compile
        env:
          MIX_ENV: test
