name: CI-Local

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache Mix dependencies
        uses: actions/cache@v3
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: Setup asdf environment
        run: |
          . /opt/asdf/asdf.sh
          asdf reshim
          elixir --version
          mix --version

      - name: Install Mix Dependencies
        run: |
          . /opt/asdf/asdf.sh
          mix local.hex --force
          mix local.rebar --force
          mix deps.get

      - name: Check Formatting
        run: |
          . /opt/asdf/asdf.sh
          mix format --check-formatted
