name: Cross-Platform Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual trigger'
        required: true
        default: 'Manual verification'

jobs:
  test:
    name: Test Raxol on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            platform: linux
          - os: macos-latest
            platform: macos
          - os: windows-latest
            platform: windows
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.14.x'
          otp-version: '25.x'

      - name: Cache deps
        uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: Install dependencies
        run: |
          mix local.hex --force
          mix local.rebar --force
          mix deps.get
          mix deps.compile
      
      - name: Run unit tests
        run: mix test test/raxol
      
      - name: Run integration tests
        run: mix test test/integration
      
      - name: Run cross-platform specific tests
        run: mix test test/platform
      
      - name: Verify terminal compatibility
        run: mix run test/platform/verify_terminal_compatibility.exs
      
      - name: Build test binary
        run: mix run scripts/release.exs --env test --platform ${{ matrix.platform }}
        env:
          MIX_ENV: test
      
      - name: Test binary functionality
        run: |
          cd burrito_out/test
          ./raxol --test-mode --verify-features

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results-${{ matrix.platform }}
          path: _build/test/results 