name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: 1.14.0
          otp-version: 25.0

      - name: Install Dependencies
        run: |
          mix local.hex --force
          mix local.rebar --force
          mix deps.get

      - name: Run Tests
        env:
          MIX_ENV: test
        run: |
          mix test
          mix credo
          mix dialyzer

      - name: Create Release
        env:
          MIX_ENV: prod
        run: |
          mix release

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            _build/prod/rel/raxol/releases/*/raxol.tar.gz
            _build/prod/rel/raxol/releases/*/raxol.tar.gz.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to Hex
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
        run: |
          mix hex.publish 