name: Test Snyk Security Scan

on: [workflow_dispatch]

jobs:
  test:
    name: Test Snyk
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      # Run security scan only on Linux runners
      - name: Run Security Scan on Linux
        uses: snyk/actions/node@master
        if: runner.os == 'Linux'
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high

      # On macOS, use the CLI installation instead of the Docker-based action
      - name: Security Scan on macOS
        if: runner.os == 'macOS'
        run: |
          # Install Snyk CLI via npm
          echo "Installing Snyk CLI via npm..."
          npm install -g snyk
          snyk auth ${{ secrets.SNYK_TOKEN }}

          # Run the security scan
          echo "Running Snyk without Docker dependencies..."
          snyk test --severity-threshold=high || echo "Snyk found issues but continuing"
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
